### ISSUE TITLE
Visualize grid properties in cross section

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface#139]
This will most likely have to be done by precalculating arrays for each well/grid property as a forward model. It is too time consuming / memory demanding to do interactively.

**Comment by anders-kiaer** [comment]
Solved in #198 I think. Please repoen @HansKallekleiv if incorrect.

**Comment by HansKallekleiv** [comment]
Still missing well cross-section, but that can be a separate issue.
